import { Box } from '@mui/material';

import DashBoardNavBar from '@/features/dashboard/dashboard-navbar/DashBoardNavBar';
import DashBoardWelcome from '@/features/dashboard/dashboard-welcome/DashBoardWelcome';

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Box sx={{ display: 'flex', direction: 'row' }}>
      <DashBoardNavBar  />
      <Box
        sx={{
          width: '100%',
          paddingTop: '42px',
          paddingLeft: '32px',
          paddingRight: '32px',
        }}
      >
        <DashBoardWelcome />
        <Box sx={{padding: '23px 0' }}>

          {children}
        </Box>
      </Box>
    </Box>
  );
}
export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
  icons: {
    icon: '/companyicon.ico',
  },
};
